### ISSUE TITLE
Bug UI Login & Registration

### ISSUE THREAD

**Issue by syatriia** [ice1217/max-2.0-ui#1]
Here some bug in UI Login and Registration

[TEST CASE UI.xlsx](https://github.com/ice1217/max-2.0-ui/files/1273488/TEST.CASE.UI.xlsx)

**Comment by ice1217** [comment]
fixed, please review for closing @syatriia

**Comment by syatriia** [comment]
i have already review that bugs and all test case already passed
then i'll close the issue

thanks for fixed the bugs @ice1217
