### ISSUE TITLE
Bug list synonym in keyword dictionary

### ISSUE THREAD

**Issue by syatriia** [ice1217/max-2.0-ui#10]
[Bug FE - 2018-10-19.docx](https://github.com/ice1217/max-2.0-ui/files/1396979/Bug.FE.-.2018-10-19.docx)

**Comment by fendydjung** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Raise bug](https://trello.com/c/lDrr7onj/66-raise-bug)

**Comment by ice1217** [comment]
fixed, please check @syatriia

**Comment by syatriia** [comment]
checked, thanks @ice1217
