### ISSUE TITLE
Add label to topic name at Source & Dictionary Page

### ISSUE THREAD

**Issue by fendydjung** [ice1217/max-2.0-ui#11]
![image](https://user-images.githubusercontent.com/20120299/31755927-426d87be-b4cb-11e7-8d53-5cc6e686bbd1.png)

**Comment by fendydjung** [comment]
![image](https://user-images.githubusercontent.com/20120299/32046412-2cf6e7b6-ba6d-11e7-82db-0f675353fbcf.png)

Change label to be capitalized.

**Comment by ice1217** [comment]
done, please review again @fendydjung

**Comment by fendydjung** [comment]
Done
