### ISSUE TITLE
Add below help text component

### ISSUE THREAD

**Issue by fendydjung** [ice1217/max-2.0-ui#12]
At Topic page:
Total Docs (?) --> Indicate total documents from sources for this topic
Sources (?) --> Show sources for this topic
Topic Details (?) _**change to**_ Details (?) --> Show details for this topic

@ice1217 Kindly advise grammar above ya.

**Comment by fendydjung** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fixing bugs UI](https://trello.com/c/r0aO1UAE/72-fixing-bugs-ui)

**Comment by ice1217** [comment]
Total Docs (?) --> Indicate the total documents from all data sources for this topic
Sources (?) --> Show all data sources for this topic
Topic Details (?) change to Details (?) --> Show details for this topic

**Comment by ice1217** [comment]
@laxen00 please add the help text components

**Comment by ice1217** [comment]
added, please review @fendydjung

**Comment by fendydjung** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix: delete topic bug](https://trello.com/c/YY3vfjHj/88-fix-delete-topic-bug)
