### ISSUE TITLE
Bug list dictionary when create collection product review

### ISSUE THREAD

**Issue by syatriia** [ice1217/max-2.0-ui#14]
[BUG FE - 25-10-2017.docx](https://github.com/ice1217/max-2.0-ui/files/1410724/BUG.FE.-.25-10-2017.docx)

**Comment by fendydjung** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fixing bugs UI](https://trello.com/c/MGfiwOGD/79-fixing-bugs-ui)

**Comment by ice1217** [comment]
problem on the dictionary API, will consult with backend for solution @syatriia @fendydjung

**Comment by ice1217** [comment]
fixed, please review @syatriia

**Comment by syatriia** [comment]
checked
