### ISSUE TITLE
Enhancement : input keyword for data source

### ISSUE THREAD

**Issue by syatriia** [ice1217/max-2.0-ui#17]
Ketika create data source, tulung add  keterangan untuk menambahkan multiple keyword
![issue005](https://user-images.githubusercontent.com/13661944/32207043-dadcb6be-be2b-11e7-9765-61fd966c72a3.png)

**Comment by fendydjung** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix bug UI](https://trello.com/c/5rsTJkUQ/18-fix-bug-ui)

**Comment by laxen00** [comment]
@syatriia please check

**Comment by syatriia** [comment]
done
