### ISSUE TITLE
Bug existing name topics

### ISSUE THREAD

**Issue by syatriia** [ice1217/max-2.0-ui#19]
Ketika user membuat topics baru dengan nama topics yang sudah ada, kemudian saya tidak bisa masuk ke halaman dashboard
![bug 3](https://user-images.githubusercontent.com/13661944/32207230-235a3e2e-be2d-11e7-8f0a-7ea412d04795.png)

**Comment by fendydjung** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix bug UI #2](https://trello.com/c/YoegLKeP/103-fix-bug-ui-2)

**Comment by laxen00** [comment]
@syatriia please check

**Comment by syatriia** [comment]
done
