### ISSUE TITLE
Bug UI Update Profil + Change Password

### ISSUE THREAD

**Issue by syatriia** [ice1217/max-2.0-ui#2]
Here some bug Update Profile and Change Password
[Report Test Update Profile + Change Password.xlsx](https://github.com/ice1217/max-2.0-ui/files/1280770/Report.Test.Update.Profil.Change.Password.xlsx)

**Comment by ice1217** [comment]
fixed, please check for closing

**Comment by ice1217** [comment]
fixed, please check for closing @syatriia

**Comment by syatriia** [comment]
i have already review that bugs and there test case is failed
here is the some bug who i found
[Report Bug Update User + Change Password.xlsx](https://github.com/ice1217/max-2.0-ui/files/1295630/Report.Bug.Update.User.Change.Password.xlsx)

**Comment by ice1217** [comment]
update, please review again thx @syatriia
