### ISSUE TITLE
Bug Dictionary

### ISSUE THREAD

**Issue by syatriia** [ice1217/max-2.0-ui#21]
Ketika create dictionary, alias diisi kosong dan ketika diklik button create, sempat muncul tulisan oops something wrong. tapi somehow dictionary ga ke create dan semua bahagia 

![issue010](https://user-images.githubusercontent.com/13661944/32207485-c79f02d4-be2e-11e7-9d68-7e3b8a8fd436.png)

**Comment by fendydjung** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix bug UI #2](https://trello.com/c/YoegLKeP/103-fix-bug-ui-2)
