### ISSUE TITLE
Enhancement : notification ketika salah login

### ISSUE THREAD

**Issue by syatriia** [ice1217/max-2.0-ui#22]
login page. ketika login salah, page seperti refresh. ngga ada notif

**Comment by fendydjung** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix bug UI](https://trello.com/c/BtGVtaia/102-fix-bug-ui)

**Comment by laxen00** [comment]
done, please check @syatriia

**Comment by syatriia** [comment]
checked
