### ISSUE TITLE
Bug Field email registration

### ISSUE THREAD

**Issue by syatriia** [ice1217/max-2.0-ui#23]
registrasi, checking email kurang mantaf

1. ketika registrasi, isi field email dengan sampah@email.
2. dll dst.
3. berhasil register.
4. berhasil login.

![issue001](https://user-images.githubusercontent.com/13661944/32210990-050e5296-be43-11e7-9b98-1f92709cb00c.png)

![issue011](https://user-images.githubusercontent.com/13661944/32210968-ecf86020-be42-11e7-86b9-af5f8b321aec.png)

**Comment by fendydjung** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix bug UI](https://trello.com/c/BtGVtaia/102-fix-bug-ui)

**Comment by laxen00** [comment]
done please check @syatriia

**Comment by syatriia** [comment]
field email sudah ada pesan error, tp masih berhasil untuk registrasi
![field email 1](https://user-images.githubusercontent.com/13661944/32310233-832f5572-bfc3-11e7-8be9-64e03abfd054.jpg)
![field email 2](https://user-images.githubusercontent.com/13661944/32310234-845ac1ca-bfc3-11e7-8f73-a122e6724d00.jpg)

**Comment by laxen00** [comment]
coba di cek lagi @syatriia

**Comment by syatriia** [comment]
checked
