### ISSUE TITLE
Bug Dictionary : Empty field name dictionary

### ISSUE THREAD

**Issue by syatriia** [ice1217/max-2.0-ui#24]
Ketika create dictionary, name dictionary bisa diisi kosong 

![bug empty name dictionary](https://user-images.githubusercontent.com/13661944/32359054-61422af6-c07d-11e7-835d-c72ae4e03481.jpg)
![bug empty name dictionary - 2](https://user-images.githubusercontent.com/13661944/32359056-6336775e-c07d-11e7-95dc-a72bc7a099c4.jpg)

**Comment by laxen00** [comment]
@syatriia please check

**Comment by syatriia** [comment]
done
