### ISSUE TITLE
Bug: button add alias

### ISSUE THREAD

**Issue by syatriia** [ice1217/max-2.0-ui#25]
Button add alias tidak bisa di click ketika membuat 2 dictionary
![bug ui - button add alias ga bisa di klik](https://user-images.githubusercontent.com/13661944/32432023-764c96c4-c308-11e7-8734-a146a1a5d927.jpg)

**Comment by fendydjung** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix bug UI](https://trello.com/c/5rsTJkUQ/18-fix-bug-ui)

**Comment by laxen00** [comment]
@syatriia please check

**Comment by syatriia** [comment]
done
