### ISSUE TITLE
Report Bug Unit Test Crawler + Change Password

### ISSUE THREAD

**Issue by syatriia** [ice1217/max-2.0-ui#4]
Here some bug when change password and add crawler
[Report Bug Unit Test Crawler + Change Password.xlsx](https://github.com/ice1217/max-2.0-ui/files/1310459/Report.Bug.Unit.Test.Crawler.Change.Password.xlsx)

**Comment by ice1217** [comment]
deployed a fix for the bugs, please review thx @syatriia
