### ISSUE TITLE
New card

### ISSUE THREAD

**Issue by syatriia** [ice1217/max-2.0-ui#6]
Here some new card from meeting on friday
[new card.txt](https://github.com/ice1217/max-2.0-ui/files/1386228/new.card.txt)

**Comment by fendydjung** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fixing bug UI](https://trello.com/c/FnElW2q6/52-fixing-bug-ui)

**Comment by ice1217** [comment]
fixed, please check @syatriia

**Comment by syatriia** [comment]
Checked
