### ISSUE TITLE
Forbidden space char for first entry in dictionary list

### ISSUE THREAD

**Issue by fendydjung** [ice1217/max-2.0-ui#7]
Entry pertama pada list dictionary tidak boleh ada spasi. Entry berikut boleh ada spasi.

**Comment by ice1217** [comment]
please provide a more thorough description

**Comment by fendydjung** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fixing bugs UI](https://trello.com/c/r0aO1UAE/72-fixing-bugs-ui)

**Comment by fendydjung** [comment]
![image](https://user-images.githubusercontent.com/20120299/31883434-1c0de658-b814-11e7-8f67-26516af6e985.png)

no space allowed in this field above

![image](https://user-images.githubusercontent.com/20120299/31883555-6ebb8842-b814-11e7-8447-e905377666bc.png)

space allowed only for alias

**Comment by ice1217** [comment]
fixed, please review @fendydjung
