### ISSUE TITLE
White Line on Dashboard page

### ISSUE THREAD

**Issue by syatriia** [ice1217/max-2.0-ui#8]
There white line between side menu and footer
[Bug FE - 2018-10-18.docx](https://github.com/ice1217/max-2.0-ui/files/1393444/Bug.FE.-.2018-10-18.docx)

**Comment by ice1217** [comment]
@laxen00 please check the aforementioned bug

**Comment by fendydjung** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fixing bugs UI](https://trello.com/c/r0aO1UAE/72-fixing-bugs-ui)

**Comment by ice1217** [comment]
fixed, please review @syatriia

**Comment by syatriia** [comment]
checked
